### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by fayalalebrun** [V0XNIHILI/few-shot-spoken-term-classification#1]
Trying to integrate this into my repository, I came across the following issue:
```
basename='speech_commands_v0.02.tar.gz'
Loading training set: 100%|█████████████████████████████████████████████████████████████████| 84843/84843 [02:13<00:00, 637.32it/s]
Traceback (most recent call last):
  File "run_train.py", line 143, in <module>
    train(parser.parse_args())
  File "train.py", line 151, in train
    ) = create_dataset_fn(args.dir_name, seed=data_seed, batch_size=args.batch_size, **kwargs)
  File "dataloading.py", line 820, in create_speech_commands_10plus2_dataset
    train_ds = FewShotSpokenTermClassification("command", "raw_datasets/", "speech_commands_v0.02", "SpeechCommands", None, False, "training")
  File "few_shot_spoken_term_classification/FewShotSpokenTermClassification.py", line 120, in __init__
    train_or_val_subset = [i for i in range(len(train_or_val_data._data)) if train_or_val_data._data[i][5] in unknown_words + ['_silence_'] + train_words]
  File "few_shot_spoken_term_classification/FewShotSpokenTermClassification.py", line 120, in <listcomp>
    train_or_val_subset = [i for i in range(len(train_or_val_data._data)) if train_or_val_data._data[i][5] in unknown_words + ['_silence_'] + train_words]
IndexError: tuple index out of range
```

Printing one such tuple in question, `print(train_or_val_data._data[0])` gives: `(tensor([[-0.0658, -0.0709, -0.0753,  ..., -0.0700, -0.0731, -0.0704]]), 16000, 11, '0165e0e8', 0)`

Perhaps the library was tested under another version of AudioLoader? I am using the latest git version.

**Comment by V0XNIHILI** [comment]
This is fixed right now right?
